.TH PUSHOVER 6 "November 17, 2008"
.SH NAME
pushover \- fun puzzle domino game
.SH SYNOPSIS
.B pushover
.br
.SH DESCRIPTION
This manual page documents briefly the
.B pushover
command.
.PP
\fBpushover\fP is a fun puzzle domino game.
.SH USAGE
The goal of the game is to let the domina stones fall and move the Ant to the exit.
.IP "Ant movements"
Left - Move left
.br
Right - Move right
.br
Down - Climb ladder; walk out of blocks
.br
Up - enter door; climb ladder; walk into a gap between blocks
.br
Space - pick up a block; drop it
.br
Space + Left/Right - push the block (after going Up)
.SH AUTHOR
pushover was written by Andreas R\[:o]ver and Volker Grabsch.
.PP
This manual page was written by G\[:u]rkan Myczko <gurkan@phys.ethz.ch>,
for the Debian project (and may be used by others).
