.TH PUSHOVER 6 "November 17, 2008"
.SH NAME
pushover \- fun puzzle domino game
.SH SYNOPSIS
.B pushover
.br
.SH DESCRIPTION
This manual page documents briefly the
.B pushover
command.
.PP
\fBpushover\fP is a fun puzzle domino game.
.SH AUTHOR
pushover was written by Andreas R\[:o]ver and Volker Grabsch.
.PP
This manual page was written by G\[:u]rkan Myczko <gurkan@phys.ethz.ch>,
for the Debian project (and may be used by others).
